### ISSUE TITLE
Not able to set sync_for_device

### ISSUE THREAD

**Issue by noelpedro** [ikwzm/FPGA-SoC-Linux-Example-2-ZYBO-Z7#1]
Hi,

I don't know why I'm ABLE to set the the sync_size in /sys/class/udmabuf/udmabuf-rx (or udmabuf-tx).

However I'm UNABLE to set the value for sync_for_device i.e. it stays at zero and dosen't change to 1 after the function call for sync_for_device.

Thanks,

**Comment by ikwzm** [comment]
Thank you for the issue.

sync_for_device and sync_for_cpu are write-only device files.
The results of sync_for_device and sync_for_cpu are reflected in the sync_ower device file.

When CPU accesses to the buffer, '1' should be written to sync_for_cpu to set CPU as the owner. Upon the write to sync_for_cpu, CPU cache is invalidated if sync_direction is 2(=DMA_FROM_DEVICE) or 0(=DMA_BIDIRECTIONAL). Once CPU is becomes the owner of the buffer, the accelerator cannot access the buffer.

On the other hand, when the accelerator needs to access the buffer, '1' should be written to sync_for_device to change owership of the buffer to the accelerator. Upon the write to sync_for_device, the CPU cache of the specified memory area is flushed using data on the main memory.

**Comment by noelpedro** [comment]
Thanks my design works now.

It’s not a loop back, but I built it on top of this example and it worked.

**Comment by noelpedro** [comment]
Hey Ichiro do the dma transactions have to be 8 bit int?

Can they be 16 bit ints?
